export enum ErrorMsgEnum {
  NOT_FOUND = 'NOT_FOUND',
  EXISTED = 'EMAIL_EXISTED',
  INVALID_PASSWORD = 'INVALID_CREDENTIALS',
  SAME_USER = 'SENDER_AND_RECEIVER_ARE_SAME',
  CONVERSATION_CREATED = 'CONVERSATION_CREATED',
  NOT_IN_CONVERSATION = 'NOT_IN_CONVERSATION',
}
